spring:
  application:
    name: rest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: super
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
session:
  packages-to-scan: ru.telanors.rest.entity
soap:
  url: http://localhost:8081/soap
  namespace: http://telanors.ru/soap/
  request-name: personRequest
  response-name: personResponse