spring:
  application:
    name: rest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: super
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
session:
  packages-to-scan: ru.telanors.rest.entity